### ISSUE TITLE
您好，我复制了cURL到postman出现了无效的cURL，可以帮我看下嘛

### ISSUE THREAD

**Issue by LYluyu** [huangke19/TikTokSpider#2]
您好，如题，参数如下

分享链接：https://v.douyin.com/c6Q9Va/

cURL:curl 'https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=MS4wLjABAAAAgq8cb7cn9ByhZbmx-XQDdRTvFzmJeBBXOUO4QflP96M&count=21&max_cursor=0&aid=1128&_signature=ns9LtBATwFDtOUHb5ox1EJ7PS6&dytk=2373bc5857d4a2286ec8d833d63340f5' -H 'authority: www.iesdouyin.com' -H 'accept: application/json' -H 'sec-fetch-dest: empty' -H 'x-requested-with: XMLHttpRequest' -H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1' -H 'sec-fetch-site: same-origin' -H 'sec-fetch-mode: cors' -H 'referer: https://www.iesdouyin.com/share/user/66598046050?u_code=h5eh0kj4&sec_uid=MS4wLjABAAAAgq8cb7cn9ByhZbmx-XQDdRTvFzmJeBBXOUO4QflP96M&utm_campaign=client_share&app=aweme&utm_medium=ios&tt_from=copy&utm_source=copy' -H 'accept-language: zh-CN,zh;q=0.9' -H 'cookie: _ga=GA1.2.484447070.1586229478; _gid=GA1.2.811684397.1586229478' --compressed

**Comment by huangke19** [comment]
我用你贴的cURL试了一下，没有问题啊，你确定是粘贴到“Paste Raw Text”的哦

**Comment by huangke19** [comment]
> 您好，如题，参数如下
> 
> 分享链接：https://v.douyin.com/c6Q9Va/
> 
> cURL:curl 'https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=MS4wLjABAAAAgq8cb7cn9ByhZbmx-XQDdRTvFzmJeBBXOUO4QflP96M&count=21&max_cursor=0&aid=1128&_signature=ns9LtBATwFDtOUHb5ox1EJ7PS6&dytk=2373bc5857d4a2286ec8d833d63340f5' -H 'authority: [www.iesdouyin.com](http://www.iesdouyin.com)' -H 'accept: application/json' -H 'sec-fetch-dest: empty' -H 'x-requested-with: XMLHttpRequest' -H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1' -H 'sec-fetch-site: same-origin' -H 'sec-fetch-mode: cors' -H 'referer: https://www.iesdouyin.com/share/user/66598046050?u_code=h5eh0kj4&sec_uid=MS4wLjABAAAAgq8cb7cn9ByhZbmx-XQDdRTvFzmJeBBXOUO4QflP96M&utm_campaign=client_share&app=aweme&utm_medium=ios&tt_from=copy&utm_source=copy' -H 'accept-language: zh-CN,zh;q=0.9' -H 'cookie: _ga=GA1.2.484447070.1586229478; _gid=GA1.2.811684397.1586229478' --compressed

无效是什么意思？是postman不能解析？还是返回的aweme_list为空？

**Comment by LYluyu** [comment]
![image](https://user-images.githubusercontent.com/16254669/78628649-564e0480-78c7-11ea-9165-970bdfd48503.png)

**Comment by huangke19** [comment]
你是不是没有把前面的cURL:复制进去？我复制你贴的内容可以正常解析，我复制的内容如下，我用三引号括起来，你对比一下：

“”“

cURL:curl 'https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=MS4wLjABAAAAgq8cb7cn9ByhZbmx-XQDdRTvFzmJeBBXOUO4QflP96M&count=21&max_cursor=0&aid=1128&_signature=ns9LtBATwFDtOUHb5ox1EJ7PS6&dytk=2373bc5857d4a2286ec8d833d63340f5' -H 'authority: www.iesdouyin.com' -H 'accept: application/json' -H 'sec-fetch-dest: empty' -H 'x-requested-with: XMLHttpRequest' -H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1' -H 'sec-fetch-site: same-origin' -H 'sec-fetch-mode: cors' -H 'referer: https://www.iesdouyin.com/share/user/66598046050?u_code=h5eh0kj4&sec_uid=MS4wLjABAAAAgq8cb7cn9ByhZbmx-XQDdRTvFzmJeBBXOUO4QflP96M&utm_campaign=client_share&app=aweme&utm_medium=ios&tt_from=copy&utm_source=copy' -H 'accept-language: zh-CN,zh;q=0.9' -H 'cookie: _ga=GA1.2.484447070.1586229478; _gid=GA1.2.811684397.1586229478' --compressed

”“”

![WechatIMG1478](https://user-images.githubusercontent.com/25167154/78629231-03754c80-78c9-11ea-8b4e-5c7e8ee85ed0.jpeg)

**Comment by huangke19** [comment]
我用你贴在上面的内容是可以解析的，我贴一下我的postman里的内容，你对比一下看是哪里格式不对


![14791586232929_ pic](https://user-images.githubusercontent.com/25167154/78629440-a8902500-78c9-11ea-94d1-ac31a3e9f735.jpg)
![14801586232941_ pic](https://user-images.githubusercontent.com/25167154/78629445-ac23ac00-78c9-11ea-9e91-8cc2a5eaedc0.jpg)

我的操作步骤
![14811586233195_ pic_hd](https://user-images.githubusercontent.com/25167154/78629623-2bb17b00-78ca-11ea-96f3-04123321d77a.jpg)

**Comment by LYluyu** [comment]
请问一下您的postman版本是多少的。是不是因为版本号不对的原因

**Comment by LYluyu** [comment]
可以了，晕，我用了谷歌的postman插件出现了这个问题。下载客户端就好了
