### ISSUE TITLE
返回的data为空是怎么回事啊 data = response.json()

### ISSUE THREAD

**Issue by SherlockgotoPY** [huangke19/TikTokSpider#3]

**Comment by huangke19** [comment]
返回为空表示你的url获取得不正确，在Devtools调试的时候，你要确认真的有返回数值再进行下一步，看我readme里面的视频演示吧

**Comment by QinXueFeng** [comment]
我确定了有返回数值但是data还是空的
是不是现在修复了

**Comment by huangke19** [comment]
> 我确定了有返回数值但是data还是空的
> 是不是现在修复了

你可以对比下代码，有更新，另外是看返回数值里面aweme_list是否有值，有值就应该不为空

**Comment by huangke19** [comment]
> 我确定了有返回数值但是data还是空的
> 是不是现在修复了

我说的返回数值是aweme_list列表

**Comment by QinXueFeng** [comment]
![image](https://user-images.githubusercontent.com/34644916/78952221-723fe900-7b07-11ea-8330-d0c906ce4cea.png)
![image](https://user-images.githubusercontent.com/34644916/78952247-8552b900-7b07-11ea-9310-65b4b801ab7e.png)

**Comment by QinXueFeng** [comment]
更新代码了，你那边是能用的吗？

**Comment by huangke19** [comment]
> 更新代码了，你那边是能用的吗？

我一直都能用啊，你在F12里取的url有错，没有加载到视频资源，aweme_list是空的，去看我视频教程里是怎么取的url

**Comment by QinXueFeng** [comment]
![image](https://user-images.githubusercontent.com/34644916/78953235-c1d3e400-7b0a-11ea-95ff-34d2802bc15e.png)

**Comment by QinXueFeng** [comment]
分享链接：https://v.douyin.com/c4UHnL/
aweme_list有值：![image](https://user-images.githubusercontent.com/34644916/78953490-9271a700-7b0b-11ea-97e6-b1f694ade832.png)
获取url: ![image](https://user-images.githubusercontent.com/34644916/78953501-9ef5ff80-7b0b-11ea-837c-d0fd39d88106.png)
结果：
![image](https://user-images.githubusercontent.com/34644916/78953576-e2506e00-7b0b-11ea-91ca-28332958cc6c.png)
不知道哪里错了

**Comment by huangke19** [comment]
> https://v.douyin.com/c4UHnL/

查了一下原因，是原来的user-agent失效了，换了个user-agent就好了，代码更新了，你拉一下

**Comment by huangke19** [comment]
> 分享链接：https://v.douyin.com/c4UHnL/
> aweme_list有值：![image](https://user-images.githubusercontent.com/34644916/78953490-9271a700-7b0b-11ea-97e6-b1f694ade832.png)
> 获取url: ![image](https://user-images.githubusercontent.com/34644916/78953501-9ef5ff80-7b0b-11ea-837c-d0fd39d88106.png)
> 结果：
> ![image](https://user-images.githubusercontent.com/34644916/78953576-e2506e00-7b0b-11ea-91ca-28332958cc6c.png)
> 不知道哪里错了

查了一下原因，是原来的user-agent失效了，换了个user-agent就好了，代码更新了，你拉一下

**Comment by QinXueFeng** [comment]
你提醒我了，应该复制自己的user-agent

**Comment by huangke19** [comment]
> 你提醒我了，应该复制自己的user-agent

 是的，我已经修改代码要求用户输入自己的user-agent了，还在优化输出，等会上传代码，那你的问题解决了嘛，我关Issues了？
