### ISSUE TITLE
下载视频报错

### ISSUE THREAD

**Issue by oaoit** [huangke19/TikTokSpider#5]
dyspider.py:146: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if name == '抖音-原创音乐短视频社区':
Traceback (most recent call last):
  File "dyspider.py", line 154, in <module>
    main()
  File "dyspider.py", line 149, in main
    download_video(index, username, name, url)
  File "dyspider.py", line 54, in download_video
    print("\r正在下载第%s个视频: %s" % (index, name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1: ordinal not in range(128)

**Comment by huangke19** [comment]
> 'ascii' codec can't decode byte

编码问题，你用的python2.7吗？如果是，加上
`import sys
reload(sys)
sys.setdefaultencoding("utf-8")`

**Comment by oaoit** [comment]
可以了，多谢。
