### ISSUE TITLE
升级完善的小建议

### ISSUE THREAD

**Issue by Foxgeek36** [huangke19/TikTokSpider#7]
这个方式对单个user账号视频的下载还是挺管用的，只是上百个账号做集中下载的话，绕不开的就是signature参数的破解了；哥们，有兴趣咱们可以一起研究研究...

**Comment by huangke19** [comment]
> 这个方式对单个user账号视频的下载还是挺管用的，只是上百个账号做集中下载的话，绕不开的就是signature参数的破解了；哥们，有兴趣咱们可以一起研究研究...

没有心思去破解signature，你如果想批量下载，可以使用无头浏览器模拟手动操作的部分
